"""Add marketsettings model

Revision ID: 50718323a45a
Revises: 2c050a5a82c9
Create Date: 2025-11-09 11:28:07.750454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50718323a45a'
down_revision = '2c050a5a82c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=False),
    sa.Column('close_time', sa.Time(), nullable=False),
    sa.Column('weekdays_only', sa.Boolean(), nullable=True),
    sa.Column('holidays', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market_settings')
    # ### end Alembic commands ###
